### ISSUE TITLE
Refactor front-end

### ISSUE THREAD

**Issue by Seikho** [paypac/node-concierge#2]
- [x] Re-style the front-end
- [x] ~~Use custom CSS instead of CSS framework~~ Turns out I suck at CSS `wontfix`
- [x] Use fetch instead of JQuery AJAX
- [x] ~~Use framework agnostic toast notifications~~ Still using an opinionated CSS framework. `wontfix`
- [x] Complete items in `REWRITE.MD`

~~Also consider replacing Knockout with React or Vue~~
18/Feb/2017: Use Knockout. Huge drop in velocity since attempting to use React for no observable gain.

**Comment by Seikho** [comment]
This is mostly done now. Closing.
